CREATE DATABASE `test` /*!40100 DEFAULT CHARACTER SET cp1251 */;

DROP TABLE IF EXISTS `test`.`user`;
CREATE TABLE  `test`.`user` (
  `USER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `LOGIN` varchar(45) NOT NULL UNIQUE,
  `PASSWORD` varchar(45) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `SURNAME` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=cp1251;

